# Generated by Django 4.2 on 2023-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dovudapp', '0004_rename_image_news_imagess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imagess',
            field=models.ImageField(upload_to='news/imagess'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
