# Generated by Django 4.2 on 2023-04-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dovudapp', '0007_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
