# Generated by Django 4.2 on 2023-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dovudapp', '0008_remove_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
